name: "cargo publish"

on:
  release:
    types: [published]
    
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login
      run: cargo login ${{ secrets.CRATES_TOKEN }}
    - name: publish
      run: cargo publish
